### ISSUE TITLE
Grid search for HMM

### ISSUE THREAD

**Issue by pavlin-policar** [petergabrovsek/ub201617_kappa#2]
Try for different length kmers for alphabets since the single nucleotide alphabet will most likely produce inadequate results.

**Comment by VikiPetrovic** [comment]
Also try for different state alphabets and try using both KST and BW trainer

**Comment by pavlin-policar** [comment]
Perhaps mixing the different length kmers might also be a good idea (if possible) e.g. mix 2mers with 3mers and such.

This might be beneficial since a nucleotitdes appear in threes, but if we look at what actually occurs in the binding sites, there are a lot of TGs in sequence, so it might be better to detect that than triplets.
